site_name: Wasatch Scale Models Docs
site_url: https://docs.wasatchscalemodels.com

theme:
  name: material
  features:
    - tabs
    - instant
  language: en
  palette: 
    primary: white
    accent: orange

repo_name: wasatchscalemodels/docs
repo_url: https://github.com/wasatchscalemodels/docs

nav:
  - Home: 'index.md'   
  - FireBox:
    - Getting Started: 'FireBox/getting_started.md'

edit_uri: ""

markdown_extensions: 
  - admonition
  - codehilite
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/wasatchscalemodels/
    - icon: fontawesome/brands/github
      link: https://github.com/wasatchscalemodels
  disqus: wasatch-scale-models

google_analytics:
  - UA-169893990-2
  - auto